
arithdemo: arithdemo.o add.o sub.o
	gcc -o arithdemo arithdemo.o add.o sub.o

arithdemo.o: arithdemo.c
	gcc -c -o arithdemo.o arithdemo.c

add.o: add.c
	gcc -c -o add.o add.c

sub.o: sub.c
	gcc -c -o sub.o sub.c